// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqaqmpamhihzzxonihcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxYXFtcGFtaGloenp4b25paGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzcxODYsImV4cCI6MjA2NTkxMzE4Nn0.MwJ7ciDc-8lY6m-JIzq4Rh4CUpJrIwgTi5sjFoZ-8cY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);